### ISSUE TITLE
DDU may sometimes hang indefinitely when inbound traffic is not allowed.

### ISSUE THREAD

**Issue by Shady7557** [Wagnard/display-drivers-uninstaller#19]
I had outbound traffic for DDU enabled, however, when inbound traffic was disabled, the program would hang indefinitely. I could not kill it with taskkill because it said "no running instance", and task manager simply failed.

As soon as I allowed inbound traffic, all the instances killed, and then when I went to run the program again, it was fine.

**Comment by Wagnard** [comment]
With windows firewall?

**Comment by Shady7557** [comment]
Yes, it simply had been blocked through Windows Firewall, and this had occurred. I never actually tried reproducing this bug, so I may have been wrong in assuming this was a more than one time thing.

**Comment by Wagnard** [comment]
I didn't try to repro this yet, but my first impression is it could be because the Checkupdate function need a timeout. (I tough there was one tho.)

**Comment by Shady7557** [comment]
I haven't been able to reproduce this again, so it ma have just been an isolated issue on my end.

**Comment by Wagnard** [comment]
I'll close this since we canot repro. But if it happens again, lets re-open it.
