### ISSUE TITLE
Normal mode restoring shouldn't depend on user access

### ISSUE THREAD

**Issue by mirh** [Wagnard/display-drivers-uninstaller#25]
In particular, yesterday I lost three hours because I was used to log in Windows with PIN, and safe mode only allows complete password, which of course I forgotten ([thankfully ](http://pogostick.net/~pnh/ntpasswd/)I avoided formatting). 

Anyway, I indeed [see](https://github.com/Wagnard/display-drivers-uninstaller/blob/master/display-drivers-uninstaller/WindowsApplication1/frmMain.vb#L6122) you depends on the program starting again to remove the bcd flag. 
And I was thinking something that could prevent similar situations should be implemented. 

Perhaps relying on a separate bcd "config" for the operation?
Or setting something that runs at "system level" to restore normal mode (app opening should in turn delete this kind of service then)?

_[some](http://www.tweaking.com/forums/index.php?topic=3195.0) [ideas](https://stackoverflow.com/questions/13276147/programmatically-reboot-in-safe-mode-then-execute-program)_

**Comment by Wagnard** [comment]
Yeah I 100% agree with you.
Idea of runOnce is already implemented and this run only when user log-on.
The other thing that could work is the service and it will require some work to be done.
The other option would be to completely remove this feature and let the user manually go into safemode.

**Comment by mirh** [comment]
> But lets be honest, I personally think that DDU is not really responsible if you loose your microsoft password heh?

Well, technically let's say it was my cousin. Anyway, that was just an example. Who knows what's then :s

Anyway, I just now realize that *Run* is still executed after log in (just for any user instead of the current one). 
It seems there are [a lot of other keys](http://superuser.com/questions/1032828/where-is-the-runservicesonce-registry-key) before that.

**Comment by Wagnard** [comment]
We will look at this. the service thing is the most probable thing I will do.

**Comment by Wagnard** [comment]
According to this : https://support.microsoft.com/en-us/kb/179365  the "RunServicesOnce" is not working anymore :(

I guess this will end with a normal service that will be remove when DDU runs. I will also have to enable Safe Mode to actually load it. (usually safe mode is quite specific for what services loads.)

**Comment by mirh** [comment]
.-.
I wonder if it wouldn't just be simpler to force the boot selection menu (aka "legacy mode" under W8/10 iirc)
Albeit this way "100%" of people would be "affected", for as much of a simple click as it would be.

**Comment by Wagnard** [comment]
I already did that in the past and the user reception was not really happy about this... I wonder why tho...

**Comment by mirh** [comment]
Perhaps.. "time window" was too short? 
I mean.. if it was 5 seconds I could even *miss* the right moment to select safe mode

**Comment by Wagnard** [comment]
If I remember correctly, some use were lost and didn't know what to do :/

**Comment by mirh** [comment]
... the fuck?
Monkeys would be able to select the right one.

**Comment by Wagnard** [comment]
Closed as we added a warning message before the user goes into safemode that their real password is required and that PIN does not work,

**Comment by mirh** [comment]
Mhh.. not exactly what I hoped, but whatever.

**Comment by Wagnard** [comment]
Yeah sorry, I know you would have liked to see the "F8" menu style but there is 1 issue that some users may had with this.
I know some users who select to have this menu always by default. And there iis no way for DDU to know about this and after the cleanUP it would remove it to thoses users.
I can already imagine the reports that DDU changed their preference etc.
So I think for now a good and evident warning should be enough.
But no worries, i'm still looking for a way to possibly set it back (safemode) to normal mode before login in.

**Comment by mirh** [comment]
> According to this : https://web.archive.org/web/20160322121721/https://support.microsoft.com/en-us/kb/179365 the "RunServicesOnce" is not working anymore :(

I feel like I got hit by a truck of stupid. 
Did you try the hint of one of my OP links to prefix an asterisk or an exclamation mark to the command?
