### ISSUE TITLE
Option dialog is cut in 800x600 resolution

### ISSUE THREAD

**Issue by mirh** [Wagnard/display-drivers-uninstaller#29]
![800x600](https://cloud.githubusercontent.com/assets/9366725/17071338/3a165426-5061-11e6-802b-f14a374c0bc7.PNG)

**Comment by Wagnard** [comment]
Thanks for the report, we will see what we can do about this.
As a workaround for the moment, you can try to set the resolution a little higher if possible.

**Comment by Wagnard** [comment]
Tested and shouldn't be an issue anymore.
Expect to see this fix in next release.
