### ISSUE TITLE
Click and forget mode

### ISSUE THREAD

**Issue by mirh** [Wagnard/display-drivers-uninstaller#30]
So.. Today I was so fucking done with driver problems that even waiting for PC to reboot, then clicking OK was a PITA. 

Would it be possible to.. I dunno, be presented with vendor choice screen before restart, then have Windows reboot in safe mode and [autolog](https://technet.microsoft.com/en-us/library/cc939702.aspx).. DDU doing his magic, last reboot?

And.. hell, I wonder if this might not help with #25

**Comment by Wagnard** [comment]
Well there is something that I will fix soon is the command line argument. 
That should at least help a bit for what you want.

I don't intend _for the moment_ to do an autolog feature.

**Comment by Wagnard** [comment]
Command line argument are now included in 17.0.1.0
