### ISSUE TITLE
DDU window is always on top and can't be minimized

### ISSUE THREAD

**Issue by mirh** [Wagnard/display-drivers-uninstaller#31]
I wouldn't know what was the rationale for either of these choices, but together they are definitively annoying.

**Comment by Wagnard** [comment]
Strange it's not happening on my end.

On what OS are you using DU and what is the version of the  .Net framework installed on your system?

Edit, this only happens on the Launch option window. Not the "MAIN" DDU Window.
I personally don't see an issue to have the "Launch option" like that.

**Comment by mirh** [comment]
Tbh I don't see why it should be like this in the first place. 
If any it would make sense in safe mode, to be on top of the "windows help guide" that usually appears at least under 7. 

But I can't find a sense in having to move it every time I want to dismiss the "do you want to reboot" question of official driver uninstaller. Or whatever else I'm doing I leave the window open.

**Comment by Wagnard** [comment]
We will look on this.
Also the reason it does that in a little complex. The main intention is not to make this windows necessary on top of everything.

**Comment by Wagnard** [comment]
Fixed by this commit : eec96daf5b94bd38830841300dd047a1e17c1837
