### ISSUE TITLE
DDU doesn't seem to stop windows from auto-downloading drivers.

### ISSUE THREAD

**Issue by dragons4life** [Wagnard/display-drivers-uninstaller#37]
Windows 10 Pro, latest update. Version 1703 - OS Build 15063.608 64 Bit

Either choosing or letting DDU choose, no longer works.

Edit: Using http://www.thewindowsclub.com/stop-windows-7-from-installing-drivers-automatically (do not use gpedit) made it work it seemed

**Comment by Wagnard** [comment]
Well this is exactly what DDU does at the moment and it is known to not be that effective.
Best way is to disconnect your internet.

**Comment by dragons4life** [comment]
Are you sure? didn't see HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\DriverSearching change at all with it at all.

Anyway this seems like microsoft being annoying as fuck again, I'll close this and hopefully people with the same problem can refer to this.

By the way using gpedit and disabling before intalling nvidia drivers seems to be the best way.
