### ISSUE TITLE
Safe mode no longer automatically offered?

### ISSUE THREAD

**Issue by mirh** [Wagnard/display-drivers-uninstaller#38]
Just opened it from W7 and it just told me "you are not, bye" - forcing me to spend 30 full seconds having to manually reboot and spam F8

**Comment by Wagnard** [comment]
You can reactivate this functionality in the DDU options.

**Comment by mirh** [comment]
_Ohh_, I [see](https://github.com/Wagnard/display-drivers-uninstaller/commit/a2a1e6e90bbb6d9b627f153bbf6b47419bc256b9#diff-9800cf9aa8812cebc30bd90aa316838dL227) even why the change now. 

I'm kind sure most translations are totally off for that button though, and that's why I had missed it. 
Maybe you should have used a new name for the string?
