### ISSUE TITLE
Roaming folder typo

### ISSUE THREAD

**Issue by mikhaelkh** [Wagnard/display-drivers-uninstaller#39]
Settings.xml Roaming folder changed from `C:\Windows\System32\config\systemprofile\AppData\Roaming\DisplayDriverUninstaller` to `C:\Windows\system32config\systemprofile\AppData\Roaming\DisplayDriverUninstaller`, seems like someone concatenated `C:\Windows\System32` and `config\systemprofile\AppData\Roaming\DisplayDriverUninstaller` and forgot to add backslash.

**Comment by Wagnard** [comment]
Thanks for reporting, I think I know what is wrong.
I'll fix this soon.

**Comment by Wagnard** [comment]
I got a repro, it will be fixed in the next version.

**Comment by Wagnard** [comment]
Fixed with this commit: 172ccb03389f97f6a9329574fc6061f3f2bf877f for next version.
