### ISSUE TITLE
Trojan found

### ISSUE THREAD

**Issue by ershov-ilya** [Wagnard/display-drivers-uninstaller#40]
http://r.virscan.org/report/88eac4a2ab60ad6318f5bc46d2c32267

I got file on website https://www.wagnardsoft.com/

<img width="969" alt="2018-01-26 16 17 42" src="https://user-images.githubusercontent.com/3964147/35441422-7f68ee60-02b4-11e8-888e-3d037af119fd.png">
<img width="966" alt="2018-01-26 16 17 53" src="https://user-images.githubusercontent.com/3964147/35441423-81388228-02b4-11e8-92de-a8b4c2cdac89.png">

**Comment by Wagnard** [comment]
Hi,
Thanks for reporting.
This is a flase positive, feel free to report it to the AV company that
flag it bad and they will fix it.
