### ISSUE TITLE
BC30456	'Threading' is not a member of 'Windows

### ISSUE THREAD

**Issue by LethalManBoob** [Wagnard/display-drivers-uninstaller#43]
Severity	Code	Description	Project	File	Line	Suppression State
Error	BC30456	'Threading' is not a member of 'Windows'.	Display Driver Uninstaller	C:\Users\User\Desktop\display-drivers-uninstaller-WPF\display-driver-uninstaller\Display Driver Uninstaller\DebugWindow.xaml.vb	616	N/A

**Comment by Wagnard** [comment]
It's an easy fix, I will post it later. Mostly just removing the "Windows" in front of threading will resolve it.

**Comment by Wagnard** [comment]
fixed by commit 265098e4f52273d093c073f46f5273aeadba58ee
