### ISSUE TITLE
Stop offering PhysX removal

### ISSUE THREAD

**Issue by mirh** [Wagnard/display-drivers-uninstaller#44]
*Perhaps* it shouldn't be removed altogether from DDU capabilities (maaaybe), but **at least** it shouldn't be ticked by default so carelessly. 

For starters, other than casually coming bundled in the nvidia drivers package.. it has pretty much nothing to do with display drivers. 
Secondly, and more importantly, PhysX is just ***so much*** [messed up](https://pcgamingwiki.com/wiki/Glossary:PhysX) already. 
And, you know, undoing the dependencies of the old games one may have installed is not helpful.

**Comment by Wagnard** [comment]
Fixed by c5f8d48bb91b13ed71d2d0b16995dddbd84a5233
