### ISSUE TITLE
Massive number of build errors. No issues cleaning. used to work fine

### ISSUE THREAD

**Issue by LethalManBoob** [Wagnard/display-drivers-uninstaller#46]
![image](https://user-images.githubusercontent.com/30273211/58480984-62b7eb80-8153-11e9-87bf-0a4f3b44916e.png)

**Comment by Wagnard** [comment]
Copy C:\Windows\System32\WinMetadata  to c:\WinMetadata

**Comment by LethalManBoob** [comment]
Worked perfectly. Thank you.
