### ISSUE TITLE
Unable to uninstall AMD drivers I think

### ISSUE THREAD

**Issue by PinKushin** [Wagnard/display-drivers-uninstaller#47]
Welp, found the github sorry for the E-mail. I will attach the Log file to this.
[2019-12-31__17-02-18_DDULog.zip](https://github.com/Wagnard/display-drivers-uninstaller/files/4013581/2019-12-31__17-02-18_DDULog.zip)

**Comment by Wagnard** [comment]
Hi, the problem is because your .NET framework in not recent enough.
Try to have at least version 4.5 or 4.6

**Comment by PinKushin** [comment]
ahh ok thanks.
Edit: I do have .Net 4.5 but it's no big deal, AMD's uninstaller worked and I was able to install Catalyst.
