### ISSUE TITLE
Realtek ASIO wont be removed

### ISSUE THREAD

**Issue by ryrun** [Wagnard/display-drivers-uninstaller#48]
Realtek added support for ASIO. DDU doesn't remove ASIO related entries from Realtek:

> Windows Registry Editor Version 5.00
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\ASIO\Realtek ASIO]
> "CLSID"="{A80362FF-CE76-4DD9-874A-704C57BF0D6A}"
> "Description"="Realtek ASIO"

**Comment by Wagnard** [comment]
Thanks I'll check this, DDU still need some work for realtek.

**Comment by Wagnard** [comment]
Added with commit : 185888152ea9c9f4c7e7e2175aa183e1965b9f45
