### ISSUE TITLE
Vulkan has more entries

### ISSUE THREAD

**Issue by mirh** [Wagnard/display-drivers-uninstaller#50]
Khronos isn't just in HKLM, but also in HKCU and Wow6432Node.

**Comment by Wagnard** [comment]
I have personally not encountered them on a NVIDIA system. I'll do some research for this with an AMD GPU too.
I guess you are with an AMD GPU?

**Comment by mirh** [comment]
Yup.

**Comment by Wagnard** [comment]
should be fixed with:  807fe70a7637f21f5237a6191c08a91013363262

**Comment by mirh** [comment]
Wait
Did you just flip on physx removal?
You are getting back to #44 now.

**Comment by Wagnard** [comment]
It is a complicated matter, some user want it to be removed by default while some other does not want so.

The main mission of DDU is to remove the driver and its packages to let the system as close as possible as if it was a clean install.
Still thinking on how I'll manage this.

**Comment by mirh** [comment]
I already explained "my" use case in the other issue. 
What's the point of other people, besides the most simple "as close as possible to a clean install" (which anyway wouldn't really be true, considering physx is installed even separated from drivers, and there's also the legacy version)?

**Comment by Wagnard** [comment]
I set the default back to false again with latest commit

**Comment by mirh** [comment]
Thanks.. If there's any problem, you can ping me.
