### ISSUE TITLE
Stop to delete amdacpksl with AMD drivers

### ISSUE THREAD

**Issue by mirh** [Wagnard/display-drivers-uninstaller#51]
It comes with realtek driver, and of course they break when you wipe the gpu one.

**Comment by Wagnard** [comment]
Can you point me the Realtek driver package that have this file? I only see this with AMD Catalyst driver.

I was able to spot some situation where it seems to come with some realtek distribution too. I'll try to see if I can identify the Realtek vs the AMD one.

If you have a system with the problem you described, can you please do a search from this key (Without A DDU run and with everything installed / working) : HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Enum    and search for a **LowerFilters** named **amdacpksl**    once/if you find it, tell me the reg path of where you found it. 
I suspect it to be under a similar location:  HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Enum\HDAUDIO\FUNC_01&VEN_10EC&DEV_1168&SUBSYS_10438723&REV_1001\4&1c71647&0&0001

**Comment by mirh** [comment]
I'm getting killed if I try any little more to "understand rather than straight fix". 

Said this.. It seems you might [be right](https://www.pconlife.com/viewfileinfo/amdacpksl-sys/) about that file ever shipping inside the graphics drivers. 
But that was the [I2S driver](https://www.amd-drivers.com/inffile-419.html), not the HDMI one. Which **imo** hasn't really much to do with graphics, and indeed newer driver packages don't have it. 
It's just shipped by realtek and/or [OEMs](https://ftp.hp.com/pub/softpaq/sp96501-97000/sp96827.exe).

**Comment by Wagnard** [comment]
For the moment, I'll follow your advise and prevent its removal as it seem to be used at many places.
I'll try to make it more intelligent in the future and remove it only when not used.
But for the moment, I'll prevent completely.

**Comment by Wagnard** [comment]
Fixed with : 0064361166d9e89cf9cebef766f6647a1aaf538d

**Comment by mirh** [comment]
Uhm? I never argued for amdacpks***d***. 
That's still shipped in modern _display_ drivers (for as much as only in the W8+ editions).

**Comment by Wagnard** [comment]
I preferred to remove it too while I was at it until further investigation.

**Comment by mirh** [comment]
They have nothing to do with each other?
Yes, they both have "ACP" in the name, but one refers to the [audio coprocessor](https://forums.guru3d.com/threads/amd-catalyst-14-7-rc1-14-200-1004-0-july-9.390979/page-15#post-4887401) *meaning* trueaudio (and that's why it ships with gpu drivers). I reckon it's just a firmware loader for the DSP. 
The other is the embedded [audio coprocessor](https://www.phoronix.com/scan.php?page=news_item&px=AMD-Linux-ACP-Audio) found in APUs.

**Comment by Wagnard** [comment]
It seem you are right, I will re-add amdacpksd in the removal process.
