### ISSUE TITLE
Build errors.

### ISSUE THREAD

**Issue by LethalManBoob** [Wagnard/display-drivers-uninstaller#52]
Yes the winmetadata is in the c:/ file path

1>------ Rebuild All started: Project: Display Driver Uninstaller, Configuration: Release Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2084,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Windows". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>C:\Users\upton\Source\Repos\display-drivers-uninstaller\display-driver-uninstaller\Display Driver Uninstaller\CleanupEngine.vb(7,9): warning BC40056: Namespace or type specified in the Imports 'Windows.Foundation' doesn't contain any public member or cannot be found. Make sure the namespace or the type is defined and contains at least one public member. Make sure the imported element name doesn't use any aliases.
1>C:\Users\upton\Source\Repos\display-drivers-uninstaller\display-driver-uninstaller\Display Driver Uninstaller\CleanupEngine.vb(8,9): warning BC40056: Namespace or type specified in the Imports 'Windows.Management.Deployment' doesn't contain any public member or cannot be found. Make sure the namespace or the type is defined and contains at least one public member. Make sure the imported element name doesn't use any aliases.
1>C:\Users\upton\Source\Repos\display-drivers-uninstaller\display-driver-uninstaller\Display Driver Uninstaller\CleanupEngine.vb(163,39): error BC30002: Type 'PackageManager' is not defined.
1>C:\Users\upton\Source\Repos\display-drivers-uninstaller\display-driver-uninstaller\Display Driver Uninstaller\CleanupEngine.vb(163,60): error BC30002: Type 'PackageManager' is not defined.
1>C:\Users\upton\Source\Repos\display-drivers-uninstaller\display-driver-uninstaller\Display Driver Uninstaller\CleanupEngine.vb(164,48): error BC30002: Type 'Windows.ApplicationModel.Package' is not defined.
1>C:\Users\upton\Source\Repos\display-drivers-uninstaller\display-driver-uninstaller\Display Driver Uninstaller\CleanupEngine.vb(164,136): error BC30002: Type 'Windows.ApplicationModel.Package' is not defined.
1>C:\Users\upton\Source\Repos\display-drivers-uninstaller\display-driver-uninstaller\Display Driver Uninstaller\CleanupEngine.vb(170,87): error BC30002: Type 'DeploymentResult' is not defined.
1>C:\Users\upton\Source\Repos\display-drivers-uninstaller\display-driver-uninstaller\Display Driver Uninstaller\CleanupEngine.vb(170,105): error BC30002: Type 'DeploymentProgress' is not defined.
1>C:\Users\upton\Source\Repos\display-drivers-uninstaller\display-driver-uninstaller\Display Driver Uninstaller\CleanupEngine.vb(170,56): error BC30002: Type 'IAsyncOperationWithProgress' is not defined.
1>C:\Users\upton\Source\Repos\display-drivers-uninstaller\display-driver-uninstaller\Display Driver Uninstaller\CleanupEngine.vb(174,65): error BC30456: 'Foundation' is not a member of 'System.Windows'.
1>C:\Users\upton\Source\Repos\display-drivers-uninstaller\display-driver-uninstaller\Display Driver Uninstaller\CleanupEngine.vb(179,69): error BC30456: 'Foundation' is not a member of 'System.Windows'.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by Wagnard** [comment]
On my side I use the Windows SDK and I have a reference linked to this:
C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.18362.0\Windows.winmd

With your file on c:\ it may work but you will have to fix the reference to match your configuration.

**Comment by LethalManBoob** [comment]
I have the same file paths and the latest windows 10 sdk

**Comment by Wagnard** [comment]
If your build error log is the same as you posted, the reference is clearly not working on your side. That is the only external reference required by DDU. It is not something I can fix on my side.

**Comment by LethalManBoob** [comment]
I found out the issue, it is because I only had 10.0.19041.0 installed, not 10.0.18362.0.
I would request that the target sdk be updated or perhaps in someway be able to dissern versions that may be higher than intended. 

Regardless the issue is fixed.
