### ISSUE TITLE
Ddu caused my games not to run properly 

### ISSUE THREAD

**Issue by therealsarkin15** [Wagnard/display-drivers-uninstaller#53]
Ever since I did a ddu. My games are now stuttering and dont feel smooth. I tried reinstalling my drivers. What do i do. I did ddu correctly. Please help

**Comment by Wagnard** [comment]
Hi, try to use the driver you had before using DDU.
DDU is not known to case stutter, usually its the driver fault or other software / drivers.

**Comment by therealsarkin15** [comment]
Am I supposed to disable the automatic driver update option from windows?

**Comment by therealsarkin15** [comment]
I tried to reinstall windows to fix the issue but it didnt work

**Comment by Wagnard** [comment]
Closing the issue then as if a Windows re-install doesn't fix your issue, this is 100% not DDU related.
