### ISSUE TITLE
Videocards - NVIDIA GeForce Drivers Section

### ISSUE THREAD

**Issue by Watcher-Guru3D** [Wagnard/display-drivers-uninstaller#56]
https://forums.guru3d.com/threads/display-driver-uninstaller-thread.379506/page-96#post-5835865

I apologize to the mods if the topic has already been covered. After using DDU with windows 2004, when I reboot after installing the drivers of the video card, windows update no longer find the drivers of my acer lcd. I wanted to know if anyone had the same thing. I thank those who want to answer. 

https://forums.guru3d.com/threads/display-driver-uninstaller-thread.379506/page-96#post-5837052

I'm having same problem. I rebooted in safe mode and removed older version of nvidia drivers. On reboot I get to windows login screen where it shows the time and I can't get pass that. After 30 seconds my pc reboots. I can get into safe mode again but not regular desktop. I'm using the latest DDU.

Edit: I did a sfc /scannow and I'm able to boot in. Weird.

**Comment by Wagnard** [comment]
Seems like user error, will close in a few day if no answer form the posters.
