### ISSUE TITLE
Great app! I've noticed a few things not removed.

### ISSUE THREAD

**Issue by Watcher-Guru3D** [Wagnard/display-drivers-uninstaller#57]
https://forums.guru3d.com/threads/display-driver-uninstaller-thread.432284/#post-5834998

C:\Users\[username]\AppData\Local\AMD_Common\addl_details_latest.json
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\AUEP
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\ATI Technologies\Install
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\ATI Technologies\Log
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\ATI Technologies\Log

**Comment by Wagnard** [comment]
I require a log for this, because theses are supposed to be removed:

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\ATI Technologies\Install
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\ATI Technologies\Log
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\ATI Technologies\Log

**Comment by Wagnard** [comment]
WIll close as the user on Guru3d did not respond and usually theses keys are supposed to be removed.
Thanks @Watcher-Guru3D for taking to time to contact me.
