### ISSUE TITLE
Add more monitor cleaning?

### ISSUE THREAD

**Issue by mirh** [Wagnard/display-drivers-uninstaller#59]
I'm very positively surprised by just how well in shape my system is, now that I DDU'ed and reinstalled the intel drivers. 
Hopefully the nightmare I was having with my external monitors is over. 

*Though*, I noticed that the [registry](https://social.technet.microsoft.com/Forums/en-US/eaad161a-1567-4e6d-b7e0-e0cf3bcd0609/reset-graphics-and-monitor-registry-settings) [keys](https://social.msdn.microsoft.com/Forums/windows/en-US/f24032ed-af5d-4caa-af62-2b43ff89a9db/where-display-properties-settings-data-are-stored-in-registry) [that](https://answers.microsoft.com/en-us/windows/forum/windows_10-hardware/windows-10-reset-external-monitors-settings/b3a53cef-e54f-4410-b09e-6846fa297a3f) store monitor configs (or should it be called cache?) isn't touched. 
Now, I'm not sure how much important they are at the end of the day (something slightly beyond the normal SetupAPI uninstallation wouldn't hurt I guess, but is it really needed to also reset the dpi settings?) but there is that.

**Comment by Wagnard** [comment]
Sorry for the massive delay about this, but DDU does already take care of the mentioned registry key. It clean the one that was In used. It will not scrapped the entire tree for safety purpose. But it does get cleaned. Can be seen in the code of cleanupengine (around line 1450)

**Comment by Wagnard** [comment]
Version 18.0.6.8 introduces a more comprehensive monitor configuration removal feature. Additionally, it will reset certain NVCP settings to their default values, impacting aspects such as resolution and scaling, among others.
