### ISSUE TITLE
Missing some MFT key

### ISSUE THREAD

**Issue by mirh** [Wagnard/display-drivers-uninstaller#60]
I noticed when I went to reinstall the latest intel drivers, that the installer was still mentioning some older keys it eventually deleted. 

I'm not really sure how much of that is *actually* deleting still-existing keys, as opposed to just "listing what keys the .inf is programmed to check", but after looking at the DDU sources I'm sure you are at least missing {00C69F81-0524-48C0-A353-4DD9D54F9A6E} and {D186A626-77CA-4D80-942F-61E0A5111AFE}, and potentially more.

**Comment by Wagnard** [comment]
Yeah the intel installer list the key to remove even if they dont exist.

**Comment by mirh** [comment]
I did found `HKCR\CLSID\{00C69F81-0524-48C0-A353-4DD9D54F9A6E}` and `HKCR\MediaFoundation\Transforms\00c69f81-0524-48c0-a353-4dd9d54f9a6e` though (and the corresponding WOW6432Node) 
Instead `HKCR\MediaFoundation\Transforms\Categories\d6c02d4b-6833-45b4-971a-05a4b04bab91\00c69f81-0524-48c0-a353-4dd9d54f9a6e` is probably going to be deleted anyway. 
And this was just the *Hardware M-JPEG Decoder*. 

If I were you I'd check some new *iigd_dch.inf* and old *igdlh64.inf* for clues.
