### ISSUE TITLE
First-Run warning dialog localization

### ISSUE THREAD

**Issue by chenyiping1995** [Wagnard/display-drivers-uninstaller#62]
https://github.com/Wagnard/display-drivers-uninstaller/blob/cfcd1bdc373bae4071684fbf59445ab85f093320/display-driver-uninstaller/Display%20Driver%20Uninstaller/frmMain.xaml.vb#L380

It seems that this Message Box regarding first-run backup was not localized and could not be localized.

Is it an intended behavior, or there are plans to implement localization?

**Comment by Wagnard** [comment]
There is plan to localization in the future for this Message box.

**Comment by Wagnard** [comment]
Added with : 68a235d9e6db906647b2ded824fe120e163e76c7
