### ISSUE TITLE
When using -Silent the program stays open after being done uninstalling

### ISSUE THREAD

**Issue by JKawmi** [Wagnard/display-drivers-uninstaller#64]
I am using "-Silent -NoSafeModeMsg -NoRestorePoint -CleanIntel -RemoveINTELCP -PreventWinUpdate" to completely remove Intel drivers and it works fine, however, when done uninstalling the program does not close itself and stays open in the background.

![image](https://user-images.githubusercontent.com/13506188/137566734-56e13152-6868-4c33-9e13-1f36962de8c3.png)

**Comment by Wagnard** [comment]
Just to inform you that we are looking into that issue.
