### ISSUE TITLE
Intel driver assistant not uninstalled

### ISSUE THREAD

**Issue by Evernow** [Wagnard/display-drivers-uninstaller#65]
Hello.

The Intel driver assistant is not uninstalled even with Intel selected (and -RemoveINTELCP passed in). 

It is located in `C:\Program Files (x86)\Intel\Driver and Support Assistant`

If any additional information is needed please say so and I will share when possible.

**Comment by Wagnard** [comment]
Hi,
"-RemoveINTELCP" is for the removal of the Intel Graphics Control panel.
DDU does not remove the "Driver and Support Assistant".
