### ISSUE TITLE
After ddu driver uninstallation and having successfully installed drivers?

### ISSUE THREAD

**Issue by crimsonduelist** [Wagnard/display-drivers-uninstaller#67]
So, after using ddu to uninstall gpu drivers and having successfully installed gpu drivers
Do you just delete the ddu folders? would I need to configure something else?

How does ddu actually stop windows from auto updating drivers, if u checked the option to stop windows from auto updating drivers
-I assume ddu sets some registry value or group policy, indicating to windows not to auto update drivers?
-Also I imagine that configuration would stay in place if I delete ddu folders if that were the case?

**Talking about the portable/zip ddu version

**Comment by Wagnard** [comment]
Hi,
The only configuration that can stay in place is if you ticked in the DDU option under Advanced options (Prevent downloads of drivers from....)

If you want to remove the DDU folder, just be sure you untick this tick box to be sure to be back at windows default,

**Comment by crimsonduelist** [comment]
nah I was gonna disable them anyway in group policies.
I was asking just to know how and what ddu actually tweaks in the system,
and to make sure deleting the zip and extracted folders wouldnt change anything.

As I see from an old post it seems is indeed the registry. https://www.wagnardsoft.com/forums/viewtopic.php?t=674
Maybe just to be safe I ll open ddu and untick -then set group policy

Anyway tnx!
