### ISSUE TITLE
"Could not find file"

### ISSUE THREAD

**Issue by KitsuneNoBaka** [Wagnard/display-drivers-uninstaller#68]
Windows 10 22H2, DDU 18.0.6.2, nVidia gtx 1080ti

![ddu error](https://user-images.githubusercontent.com/32077122/233848353-77bd2ed4-f10d-4f1b-9b0b-a5142f768cfa.png)

[2023-04-23__16-52-13_DDULog.zip](https://github.com/Wagnard/display-drivers-uninstaller/files/11304084/2023-04-23__16-52-13_DDULog.zip)

**Comment by Wagnard** [comment]
hi, this is an issue with the installer file when I released it at first. simply redownload it from my website, the file has been updated since. The portable file version is also valid. you can get the official files from : https://www.wagnardsoft.com/forums/viewtopic.php?t=4460
