### ISSUE TITLE
AV1 in Edge stopped working after purging Intel and Nvidia

### ISSUE THREAD

**Issue by ghost** [Wagnard/display-drivers-uninstaller#75]
AV1 in Edge stopped working after purging Intel and Nvidia

Please help fix.

It's a desperate situation, life and death.

The medical training portal has been converted to av1 and it's not playing.

Help.

**Comment by Wagnard** [comment]
hi, please attach the DDU logs.
in edge, do you see an error message?  white page?
Try in another browser to see if it work.

**Comment by Wagnard** [comment]
Possibly not a DDU issue : https://answers.microsoft.com/en-us/microsoftedge/forum/all/microsoft-edge-update-version-117-can-no-longer/04152acf-2b93-4cf0-ab4a-d4c72aac44e1

It seem it could be more a recent update to edge 117+ that broke AV1 compatibility.

**Comment by Wagnard** [comment]
FYI Edge beta version (121) seems to have fixed the issues with AV1

**Comment by ghost** [comment]
Thanks you are a lifesaver.
