### ISSUE TITLE
Context around why this is useful

### ISSUE THREAD

**Issue by jcrben** [Wagnard/display-drivers-uninstaller#76]
Can you provide a couple major examples where removing these drivers and all their leftovers is needed? Do versions step on each other or something? Is this still particularly relevant in 2024? Does it have much overlap with https://github.com/lostindark/DriverStoreExplorer?

Apologies if this seems obvious, I've spent a lot of my time over the past decade running macOS or Linux, but now in Windows a lot.

**Comment by Wagnard** [comment]
Driver Store explorer will remove the previous drivers from the driver store only.
DDU will remove that and also others files and registry keys related to the driver and can in the run if it encounter that fix some folder / registry permission that are incorrect and prevent driver installation.

For casual/normal users, DDU would be recommended in 2 scenarios.
1- If you encounter problem installing or uninstalling a driver via the manufacturer (Nvidia, AMD, intel, etc..) driver installer. Some weird issues like driver crashing , DDU could be able to help if it's a result from a conflicting registry key from an older driver or something around that.
2- Switching brand. You will recover disk space for completely unused driver laying around and help unclogged the registry a little. Some user mentioned that having 2 brand driver installed at the same time could lead to issues. Personally I didn't encounter that if I uninstaller the driver before.

Hope that helps a little.
But generally I could say that DDU is not mandatory.. It's mostly good practice and helping keep your computer clean.
