### ISSUE TITLE
Silent switch keeps DDU open after uninstall

### ISSUE THREAD

**Issue by Rev4N1** [Wagnard/display-drivers-uninstaller#80]
On 18.0.7.9 the silent switch worked as expected, uninstall whatever specified alongside -Silent and DDU closes itself after its done.

From 18.0.8.0 and newer, the uninstall process happens, but after its done the app keeps open in the background, never closes itself.

**Comment by Wagnard** [comment]
Thanks for reporting I will look at this.

**Comment by Wagnard** [comment]
Fixed with 98b18d33f79637762a9702c949fdff57282a643e
Will be part of 18.0.8.2 that will be release soon.
