### ISSUE TITLE
Installer - Enable multilanguage UI

### ISSUE THREAD

**Issue by bovirus** [Wagnard/display-drivers-uninstaller#82]
@Wagnard 

Thanks for your porogram.
The program has a GUI multilinguage.
Could you please consider to make installer multilanguage?
I can help with strings for Italian language.

Thanks.

**Comment by Wagnard** [comment]
Look like you fixed it yourself with a222ccb40ff83a6a0473efb62b69af8489e9fc99
I will look at adding more languages when I have time.
Or if you feel like doing so, feel free to do it :)
