### ISSUE TITLE
GUI with some part not translated

### ISSUE THREAD

**Issue by bovirus** [Wagnard/display-drivers-uninstaller#83]
@Wagnard 

In the main UI theer are some parts not traslated

![image](https://github.com/user-attachments/assets/751c9a2c-4489-4d28-924b-d51ac5d3ff51)

Highlighted there is a term not translated

In red box there are some graphic parts that I believe cannot be translated.
Could you please consider to find a way to translate them?

Thanks.

**Comment by Wagnard** [comment]
I'll check to make it translatable. For the "Update Driver Driver" we cannot do it easily as this is just an image.

**Comment by Wagnard** [comment]
For your information it was already translatable. I did make the changes for French and Italian. d4f06a8d76541ab8499f0e34d255893e020a32df

**Comment by bovirus** [comment]
@Wagnard 

Thanks.

Where can I get original master English file (English.xml)?

**Comment by Wagnard** [comment]
English.xml is on the default directory where most source files are.
![image](https://github.com/user-attachments/assets/b8e40615-5da7-4dda-83fc-d533e6b3f0d1)

**Comment by bovirus** [comment]
@Wagnard

Thanks for the info.
Please consider for the futirue if is not usful to have English.xml in Language folders (as it happen for program installation).
