### ISSUE TITLE
Updating via winget fails "Installer hash does not match"

### ISSUE THREAD

**Issue by BitGrub** [Wagnard/display-drivers-uninstaller#87]
![image](https://github.com/user-attachments/assets/bb5fdf7a-c48b-42ac-a832-fe19fd725f1c)
Something went wrong in the latest update and the installer doesn't match the expected hash

**Comment by Wagnard** [comment]
18.0.8 7 is not even the latest version.
Also I'm not the one maintaining the winget

**Comment by BitGrub** [comment]
oh.. well nevermind then, my bad 😅
